
feature: "germinal"
task_type: "binary"
magnification: "10x"
loss: ["wCE"]
name: "$model_$augment-" 
ratio: 0.9
batch_size: 4
image_dims: 1024
epochs: 100
augmentation: 
        methods: [["Flip","Rotate90","StainAugment"]]
        saturation: [0.5,1.2]
        brightness: 0.4
        hue: 0.05
        contrast: [0.8,1.5]
        flip_prob: 0.5
        rotate_prob: 0.5
        color_prob: 0.5
normalize:
        methods: ["Scale"]
        channel_std: [0.164,  0.248, 0.178]
        channel_mean: [0.791, 0.663, 0.825]        
num_classes: 1 
weights: [321.05]
model: 
        network: "unet"
        filters: [32,64,128,256,512]
        final_activation: "sigmoid"
        dropout: 0
learning_rate: 0.001 
gpu_num: 2
metric: "dice_coef" 
threshold: 0.75
early_stopping:
        metric: [0.85,0.8]
        epochs: [40, 80]
step: 512
